### ISSUE TITLE
Cache busting for script, style and template files

### ISSUE THREAD

**Issue by ejain** [CaryLandholt/AngularFun#17]
In addition to concatenating and minimizing files, it would be useful to have file checksums inserted into file names. This allows caching without constant revalidation. For example, scripts.min.js would be renamed to scripts-1234567890abcdef.min.js. There may be existing grunt tasks to help with this.

**Comment by CaryLandholt** [comment]
Hi @ejain,

There is already a cache buster for scripts and styles that is used during a prod build.

``` html
<link rel="stylesheet" href="/styles/styles.min.css?_=v<%= config.uniqueVersion() %>" />
<!--
  example:
  <link rel="stylesheet" href="/styles/styles.min.css?_=v98743256" />
-->

<script src="/scripts/scripts.min.js?_=v<%= config.uniqueVersion() %>"></script>
<!--
  example:
  <script src="/scripts/scripts.min.js?_=v24359078"></script>
-->
```

As you can see, the `config.uniqueVersion()` function inserts a unique string during every prod build as a querystring.

Templates are inlined (inserted into index.html as script tags).  Since index.html should always be served, the user will receive the latest templates.

Cache busting was left out of dev builds.

Does this satisfy your need?

Thanks,
Cary

**Comment by ejain** [comment]
Can I use <%= config.uniqueVersion() %> in stylesheets and scripts, too, e.g. to reference images?

Having the cache buster in the file name (e.g. /scripts/scripts-v24359078.min.js) rather than appended as a query parameter would ensure that the original version of the file can't end up being cached in place of the new file, e.g. when rolling out an update.

Also, using per-build strings as cache busters means that scripts and styles have to be reloaded whenever a typo in an html file is corrected, but that's a minor issue (at least for small sites).

**Comment by CaryLandholt** [comment]
Is your expectation to create a hash as the file name based on its contents?

This would ensure the file name would remain the same for each build unless the contents of that file changed.

For example:

``` CoffeeScript
# scripts.coffee
console.log 'cary'
```

when built could generate `scripts-v12345.min.js`

Then if the contents of the script were changed to:

``` CoffeeScript
# scripts.coffee
console.log 'eric'
```

when built could generate `scripts-vabcde.min.js`

Then changing the contents back to:

``` CoffeeScript
# scripts.coffee
console.log 'cary'
```

when built could generate `scripts-v12345.min.js` - the same as the first time

This way the user's browser would make the request only if the file name changed.

Was this your thinking?

As for using `config.uniqueVersion()` in stylesheets for images, you would need to make some modifications.  Currently the template grunt task is executing the function.  I haven't tried it for stylesheets, just templates/html.

**Comment by CaryLandholt** [comment]
I did something like this several months ago.
https://github.com/CaryLandholt/AngularFun/blob/162b9ab87805abfe9fb2ee24c8bb34e14a972c30/grunt.js

Cannot remember why I removed it.  :)

**Comment by ejain** [comment]
Yes, that's the idea. The Ruby on Rails asset pipeline uses this approach, as do some big sites like Facebook.

**Comment by CaryLandholt** [comment]
@ejain,

I just added cache busting to the project.

Take a look at [index.template](https://github.com/CaryLandholt/AngularFun/blob/master/src/index.template).

You'll see the following.

``` html
<script src="/scripts/scripts.min.js?v=<%= config.hash('./temp/scripts/scripts.min.js') %>"></script>
```

The `config.hash` function gets the contents of the file, passed as a parameter, and calculates a hash.  Then the hash is just appended to the end of the url as a QueryString parameter.

Hope this helps!

Thanks,
Cary

**Comment by ejain** [comment]
Perfect! Presumably I can do this, too:

``` html
<script src="/scripts/scripts-<%= config.hash('./temp/scripts/scripts.min.js') %>">.min.js</script>
```

**Comment by CaryLandholt** [comment]
No.  You won't have the hash to create the filename.
For instance, `/scripts/scripts-hashhere.min.js` does not exist until you generate the hash.
This is why I chose to go the QueryString route, since the system can generate `/scripts/scripts.min.js` without the need of the hash.  Then generating the hash is used just for the QueryString.

``` html
<script src="/scripts/scripts.min.js?v=<%= config.hash('./temp/scripts/scripts.min.js') %>"></script>
```

To do what you are asking would require generating the hash twice.  Once for the file name and once for the reference to the file.
