### ISSUE TITLE
Curious about usage of domReady!

### ISSUE THREAD

**Issue by Iristyle** [CaryLandholt/AngularFun#2]
I'm not sure that [bootstrap.coffee](https://github.com/CaryLandholt/AngularFun/blob/master/src/scripts/bootstrap.coffee) serves much of a purpose, but wasn't sure if you ran into a particular issue?

Waiting on domReady! should not be necessary to bootstrap the app, as the ngApp directive already hooks the jQuery document ready and inits the app.  See 
- [Getting rid of main blog post](http://blog.angularjs.org/2012/08/getting-rid-of-main.html)
- [angularInit function](https://github.com/angular/angular.js/blob/master/src/Angular.js#L858)

Then the snippet where angularInit is called (not sure where the source file is on GitHub, but its toward the end of the actual built angular.js file)

``` javascript
 //try to bind to jquery now so that one can write angular.element().read()
  //but we will rebind on bootstrap again.
  bindJQuery();

  publishExternalAPI(angular);

  jqLite(document).ready(function() {
    angularInit(document, bootstrap);
  });
```

I was using your method, but I see that the app ends up getting bootstrapped twice.

Now I have a choice of either removing the `ngApp` directive from my `<html>` tag **OR** removing domReady and the manual call to `angular.bootstrap`.

I tried removing the manual call to `angular.bootstrap` and didn't notice any ill effects.  I am using Require, jQuery, Lawnchair, Twitter Bootstrap, modernizr, etc...  and the dependency graph is being concatenated together by r.js without any script errors, etc. 

But again, if you ran into any real world issues, I'd love to hear it.

**Comment by samvtran** [comment]
As an aside, the file you mention is [angular.suffix](https://github.com/angular/angular.js/blob/master/src/angular.suffix) I believe.

I removed the bootstrap from a personal project without any adverse effects either (so far anyway) after realizing everything was getting bootstrapped twice on my end too. Actually, it looks like [index.template](https://github.com/CaryLandholt/AngularFun/blob/master/src/index.template) might not use ngApp, which could explain it.

**Comment by CaryLandholt** [comment]
@samvtran Yes, you are right - I'm not using the ng-app attribute, so I'm not experiencing double-bootstrapping.

@Iristyle I had to bootstrap the app manually (not use ng-app attribute) since I was loading many files asynchronously via RequireJS.  Angular begins wiring up the Angular goodness before all of my files are loaded, leading to unexpected behavior.  For all intents and purposes the dom is ready; however, it's not ready for Angular.

I have a grunt command `grunt prod` which minifies all js files.  If you then do `grunt server`, everything works fine when using the ng-app attribute since nothing is loaded async.
But when you do `grunt dev` or just `grunt` all of the separate non-minified js files are used, and we run into trouble.

Using the domready RequireJS plugin filled the gap I had.

So @Iristyle, since you are running your files through r.js you wouldn't experience a problem with using the ng-app attribute.

I hope this clarifies things.  By the way, I only need this really during development to work on non-minified, separate files.

**Comment by Iristyle** [comment]
Roger that... it all makes sense now ;0  Obviously I missed that you weren't using `ng-app`.  I've taken bits and pieces from a variety of sources, so also forgot that you weren't running your dev build through r.js.

My build has some variations on yours.  I figured I'd go ahead as part of a dev build and perform the same r.js concatenation, so what a dev sees is closer to what will be in production.  Note that I'm not uglifying it during dev, so it's still perfectly readable.  This _might_ prove to be too slow over time, but for now, it's fast enough.

I'm not sure if you realize this, but r.js emits `sourceURL` comments like this

``` javascript
//@ sourceURL=/services/foo.js
```

I'm not sure what you're debugging with, but Chrome Canary (which is generally all that I use) perfectly understands these and will show the resultant files separately in the sources browser.

Your shimmed 3rd party stuff will still end up as a big blob in your resultant file, but anything you hand-wrapped as AMD will show up just fine as 'virtual files'.

**Comment by CaryLandholt** [comment]
Thanks @Iristyle - I'll have to try the SourceMap functionality.  :)
