### ISSUE TITLE
angular as script tag

### ISSUE THREAD

**Issue by mattfysh** [CaryLandholt/AngularFun#20]
If you were to add angular as a script tag on the page, and then your require.js after that, you could avoid having to list angular as a dependency of each library. I'd imagine you could simply write this in your shim:

``` coffeescript
shim:
  'bootstrap': ['module1', 'module2', 'module3'] # all your modules listed here
```

**Comment by CaryLandholt** [comment]
@mattfysh

Yes, you are right.  It's really a trade-off and also a personal preference.  Explicitly define dependencies vs. assume the dependencies are available.
Sometimes the dependencies are non-Angular as well (i.e. jQuery, etc.).  Then you'll need to make the same decision.  Do you ask RequireJS to load and make available jQuery for you, or assume it's there?  You'll also need to handle Angular plugins (i.e. angular-resource.js) since they have a dependency on Angular.

I personally choose to define the dependencies for each component in the shim section.  It's not a lot of trouble since it's only done once for that component.  Then whenever I want a component I just ask for it.

Please note that you may potentially have a collection of module definitions with modules your particular app doesn't need but are defined nonetheless.  For example:

``` CoffeeScript
shim:
  'app': deps: ['angular']
  'module1': deps: ['app']
  'module2': deps: ['app', 'module1']
  'module3': deps: ['app']
  'module4': deps: ['app', 'module3']
  'module5': deps: ['app']
  'module6': deps: ['app', 'module5']
[
  'module1',
  'module4'
]
```

With the config above, modules 1-6 have been defined with their dependencies.  But the app is only requesting modules 1 and 4.

So the only modules that will be loaded are (in order):
1. angular
2. app
3. module1
4. module3
5. module4

The reason I bring this up is to illustrate the separation of concerns.  The shim section defines module dependencies.  The array (below the shim section) contains the modules to actually load along with any of their dependencies.

Hope this helps.

Thanks,
Cary
