### ISSUE TITLE
Upgrade reload task to work with grunt 0.4.0.

### ISSUE THREAD

**Issue by CaryLandholt** [CaryLandholt/AngularFun#27]
Would prefer to use [grunt-contrib-reload](https://github.com/gruntjs/grunt-contrib-livereload).

**Comment by CaryLandholt** [comment]
Fantastic!  Works great, but I cannot get livereload to work after restarting the express server.
Does it work for you?  I can refresh the browser manually, and all is fine.  It just doesn't reload itself when server.coffee or routes.coffee change.

By the way, thanks so much - great work!

Cary

**Comment by CaryLandholt** [comment]
Jan,

I'd like to add you as a contributor in the package.json file.
Would you mind adding yourself (name, email, url)?

Thanks,
Cary

**Comment by knalli** [comment]
Well, I've tried this, too.

With 

``` diff
diff --git a/Gruntfile.coffee b/Gruntfile.coffee
index 8806090..00acd9f 100644
--- a/Gruntfile.coffee
+++ b/Gruntfile.coffee
@@ -275,7 +275,7 @@ module.exports = (grunt) ->
                                ]
                        server:
                                files: ['server.coffee', 'routes.coffee']
-                               tasks: ['express-restart:livereload']
+                               tasks: ['express-restart:livereload', 'livereload']

                # Runs a web server at the specified port.
                # Can optionally watch for changes to the file referenced in the watch setting.
```

it will reload. But it does not wait until the server was restarted.

**Comment by CaryLandholt** [comment]
I see - so it reloads before the server is ready>

**Comment by knalli** [comment]
Documentation of grunt-express says, that is uses https://github.com/nodejitsu/forever-monitor internally. Perhaps we could give that a try..?

**Comment by CaryLandholt** [comment]
Well, it's really not a big deal, in my opinion.  If the user makes changes to the server or routes files, the user just needs to manually refresh the browser.

If you can figure it out, fantastic.  I'm thinking to just close the issue for now.

Thoughts?

**Comment by knalli** [comment]
In the future/ on demand, you could add some additional express &
connect magic: session aware, gzip, proxy support to avoid SOP
violating XHRs.

 But for now, that's enough.

**Comment by CaryLandholt** [comment]
Great - closing this issue.

Thanks, Jan!

**Comment by Bochenski** [comment]
Hi, @knalli, great that your helping with Angular Fun.  @CaryLandholt - sorry I've been quiet recently.

I've also been working on getting express to reliably restart in conjunction with live reload.  I'd come across grunt-express but hadn't got it working well myself (so thanks for the PR - really useful).  What I had done however, in my attempts to write a "live reload compatible" "restart express" type task -  was to use grunt events to listen for data coming out of stdout from express letting us know it's started, and using that as the trigger to call done() on the async grunt task.  Something along the lines of:

```
grunt.registerTask 'startServer', 'Start the express app.', () ->

    started = false
    done = this.async()

    server = require('child_process').exec './node_modules/.bin/coffee ./dist/server/server.coffee 3005'

    grunt.log.writeln 'Test server launched pid: ' + server.pid
    grunt.config.set 'serverPID', server.pid

    server.stdout.on 'data', (data) ->
      if not started
        started = true
        done()

      grunt.log.writeln data

    server.stderr.on 'data', (data) ->
      if not started
        started = true
        done()

      grunt.log.writeln data

    server.on 'exit', (code, signal) ->
      grunt.event.emit("exit-testserver")
      if not started
        started = true
        done()

```

I also log the PID into grunt config, and take the opportunity to register an event in the case that the server exits -  so that I can have a stop server task that looks a bit like this

```
  grunt.registerTask 'stoptServer', 'Stop the test server', () ->
    done = this.async();
    pid = grunt.config.get 'serverPID'
    if pid
      grunt.event.on 'exit-server', () ->
        grunt.event.removeAllListeners 'exit-server'
        grunt.log.writeln "server exited"
        done()

      try
        process.kill pid
      catch e
        {}
    else
      grunt.log.writeln 'no test server found'
      done()
```

I haven't by any stretch got this stable enough yet to PR into AngularFun.  But as you seem to have given lots of thought to this, I thought I'd share where I'd got to so far, in case any of it gave you inspiration :-)

**Comment by knalli** [comment]
Hm.. I'm not familiar with the Grunt events.

btw, it seems that reload is suggested/planned for https://github.com/gruntjs/grunt-contrib-connect.
