### ISSUE TITLE
grunt copy makes broken png files

### ISSUE THREAD

**Issue by hego** [CaryLandholt/AngularFun#3]
When I run the `grunt bootstrap` command, all the subcommands execute successfully and I can view the result in the browser. The png files are also copied to the right location, but they seem to get broken by grunt's copy command.

Is anyone else having this issue?

**Comment by CaryLandholt** [comment]
Can you share what you mean by broken?  Can you open the copied pngs in an image editor?
Do other images load properly?

Thanks

**Comment by hego** [comment]
The resulting images are corrupt, so I cannot open them in an editor. The copied files are also approx. twice the size (24912 byte for glyphicons-halflings.png, should be 13826). I then tried it with a jpg, same problem.

**Comment by CaryLandholt** [comment]
@hego Found the bug!  The grunt:copy task was using `grunt.file.write` to copy the file to its destination.
I changed this to `fs.readFileSync` and the bug was fixed.

The only change to AngularFun is in the package.json file referencing the new version of [grunt-hustler](https://github.com/CaryLandholt/grunt-hustler), where the bug fix is made.

Please get latest and give it a go.

Thanks,
Cary
